Fix choose an image button
When a new instance of ImageViewer is started, the "Choose an image"
does not work.  A traceback is in log;

Traceback (most recent call last):
  File "/usr/share/sugar/activities/ImageViewer.activity/ImageViewerActivity.py", line 396, in _show_picker_cb
    if not self._want_document:
AttributeError: 'ImageViewerActivity' object has no attribute '_want_document'

Regression caused by d496604 which removed the initialisation of the
attribute from the object.